In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("banknote-authentication.csv")
df

variance      skew  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [6]:
df.isnull().sum()

variance    0
skew        0
curtosis    0
entropy     0
class       0
dtype: int64

In [7]:
x=df.drop("class",axis=1)

In [8]:
y=df["class"]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=1)
len(x_train)

960

In [10]:
len(x_test)

412

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [12]:
x_train[:5]

array([[ 0.10527877, -0.27983064,  0.2259937 ,  0.78802844],
       [-0.99840564, -1.18889897,  1.31324557,  0.52830217],
       [-0.4363023 , -0.32105208, -0.31909545,  0.38825872],
       [-0.89636532, -0.1601366 , -0.42463686,  0.0335318 ],
       [-1.03559558, -0.38650242,  0.03167312,  0.33828751]])

In [13]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=50,criterion="gini")
classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=50)

In [14]:
x_test[:5]

array([[-1.42641109, -0.01259638, -0.26590547, -0.60744898],
       [ 0.30902392,  0.45060969,  0.2490404 ,  0.66464143],
       [-1.59283782, -1.79639493,  2.73241391, -0.12872913],
       [-1.98604462,  0.8180011 , -0.32370234, -2.55386452],
       [ 1.13616086, -0.20172327,  0.08632044,  0.92745548]])

In [15]:
y_test[:5]

1240    1
703     0
821     1
1081    1
37      0
Name: class, dtype: int64

In [16]:
classifier.score(x_test,y_test)

0.9927184466019418

In [17]:
y_pred=classifier.predict(x_test)
y_pred[:5]

array([1, 0, 1, 1, 0], dtype=int64)

In [18]:
import pickle

In [19]:
pickle_out=open("classifier.pkl","wb")
pickle.dump(classifier,pickle_out)
pickle_out.close()

In [20]:
classifier.predict([[2,3,4,0.2]])

array([0], dtype=int64)